// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Graphomania.AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class СохранениеОбъектногоГрафаВБД_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SaveObjectGraphToDatabase.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Сохранение объектного графа в БД.", "Для удобства и гибкости тестирования сценариев, когда используются сложные объект" +
                    "ные графы\r\nКак программист, аналитик или тестировшик,\r\nЯ хочу иметь средство пос" +
                    "троения объектных графов при помощи самого SpecFlow.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Сохранение объектного графа в БД.")))
            {
                Graphomania.AcceptanceTests.СохранениеОбъектногоГрафаВБД_Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Сохранение объектного графа.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Сохранение объектного графа в БД.")]
        public virtual void СохранениеОбъектногоГрафа_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Сохранение объектного графа.", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Тип объекта",
                        "Аргументы конструктора",
                        "Имя экземпляра",
                        "Связан с",
                        "Метод присвоения"});
            table1.AddRow(new string[] {
                        "HeatingNetwork",
                        "ctor: \"Теплосеть 1\"",
                        "network",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "HeatingSource",
                        "ctor: \"Котельная 1\", network",
                        "hs1",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "ConnectionPoint",
                        "method: \"p1\"",
                        "hs1-point1",
                        "hs1",
                        "CreateConnectionPoint"});
            table1.AddRow(new string[] {
                        "Location",
                        "ctor:",
                        "location1",
                        "hs1-point1",
                        "Point"});
#line 11
 testRunner.Given("существует объектный граф, описанный таблицей, объекты лежат в сборке \"DomainMode" +
                    "l\":", ((string)(null)), table1, "Допустим ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Имя экземпляра",
                        "Свойство",
                        "Значение"});
            table2.AddRow(new string[] {
                        "network",
                        "Description",
                        "\"Тепловая сеть\""});
            table2.AddRow(new string[] {
                        "hs1-point1",
                        "Location",
                        "@location1"});
#line 17
 testRunner.And("свойства объектов содержат следующие значения:", ((string)(null)), table2, "К тому же ");
#line 22
 testRunner.Then("он будет сохранен в БД,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 23
 testRunner.But("после загружен заново,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "А ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Имя экземпляра",
                        "Связан с",
                        "Через"});
            table3.AddRow(new string[] {
                        "hs1",
                        "hs1-point1",
                        "ConnectionPoints"});
            table3.AddRow(new string[] {
                        "hs1-point1",
                        "hs1",
                        "Owner"});
            table3.AddRow(new string[] {
                        "location1",
                        "hs1-point1",
                        "Point"});
            table3.AddRow(new string[] {
                        "hs1-point1",
                        "location1",
                        "Location"});
#line 25
 testRunner.And("тогда в загруженном графе объекты будут связаны между собой так, как указано в та" +
                    "блице", ((string)(null)), table3, "И ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Имя экземпляра",
                        "Свойство",
                        "Значение"});
            table4.AddRow(new string[] {
                        "network",
                        "Description",
                        "\"Тепловая сеть\""});
            table4.AddRow(new string[] {
                        "hs1-point1",
                        "Name",
                        "\"p1\""});
#line 31
 testRunner.But("свойства этих объектов будут имеють значения:", ((string)(null)), table4, "А ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
